#!/bin/sh

if [ "$(ls -A /app/texlive)" ]; then
  architecture_type=$(uname -m)
  perl_version=$(ls /app/texlive/lib/perl5/site_perl/)

  if ! [[ $perl_version =~ ^[0-9.]+$ ]]; then
    echo " WRAPPER: Possible error in environment variables."
    echo " "
  fi

  PATH=/app/texlive/bin/${architecture_type}-linux:${PATH}
  export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/app/texlive/lib/perl5/${perl_version}/${architecture_type}-linux/CORE
  export PERL5LIB=/app/texlive/lib/perl5/${perl_version}:/app/texlive/lib/perl5/site_perl/${perl_version}
fi

export PATH

exec texmaker-bin "$@"
